import Image from "next/image";
import { ShieldCheck } from "lucide-react";

import LoginForm from "@/components/admin/auth/LoginForm";

export const metadata = { title: "Ingia", description: "Ingia kwenye dashibodi ya usimamizi wa taarifa za Mlele." };

export default function LoginPage() {
  return <main className="relative grid min-h-screen overflow-hidden bg-[#f6f8f7] lg:grid-cols-2"><section className="relative hidden overflow-hidden bg-[#004b2a] p-12 text-white lg:flex lg:flex-col lg:justify-between"><Image src="/images/mkurugenzi_banner.png" alt="" fill className="object-cover opacity-20" priority /><div className="relative flex items-center gap-3"><Image src="/images/mlele-logos.jpeg" alt="Nembo ya Mlele" width={48} height={48} className="rounded-full" /><span className="font-bold">Halmashauri ya Wilaya ya Mlele</span></div><div className="relative max-w-lg"><span className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-sm"><ShieldCheck className="h-4 w-4 text-[#f5cc53]" /> Eneo salama la wasimamizi</span><h1 className="mt-6 text-5xl font-bold leading-tight">Simamia taarifa za wananchi kwa uwazi.</h1><p className="mt-5 text-lg leading-8 text-emerald-50/80">Ingia kwenye kituo cha usimamizi ili kufuatilia, kuchunguza na kutoa mrejesho wa taarifa.</p></div><p className="relative text-sm text-emerald-50/60">© {new Date().getFullYear()} Halmashauri ya Wilaya ya Mlele</p></section><section className="flex items-center justify-center p-5 sm:p-8"><div className="w-full max-w-md"><div className="mb-8 lg:hidden"><div className="flex items-center gap-3"><Image src="/images/mlele-logos.jpeg" alt="Nembo ya Mlele" width={44} height={44} className="rounded-full" /><span className="font-bold text-slate-950">Halmashauri ya Wilaya ya Mlele</span></div></div><div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-xl shadow-emerald-950/5 sm:p-8"><p className="text-sm font-semibold text-[#006b3c]">KARIBU TENA</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-slate-950">Ingia kwenye dashibodi</h2><p className="mt-3 text-sm leading-6 text-slate-500">Tumia akaunti yako ya msimamizi kuendelea.</p><div className="mt-8"><LoginForm /></div></div></div></section></main>;
}
